// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/card_draw/data/models/topic_card_entity.dart';
import 'features/practice/data/models/practice_session_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 2975515762120396459),
    name: 'CustomCategoryEntity',
    lastPropertyId: const obx_int.IdUid(5, 5363078101718647647),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2766497964249915091),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2669151000379710813),
        name: 'categoryId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 9222948346877948181),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3941976873558355656),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6700977375201004493),
        name: 'iconEmoji',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5363078101718647647),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'cards',
        srcEntity: 'TopicCardEntity',
        srcField: 'customCategory',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 974969171287862965),
    name: 'PracticeSessionEntity',
    lastPropertyId: const obx_int.IdUid(8, 8072886828325200849),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 377476718960749455),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7435866734338730424),
        name: 'sessionId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(2, 7377871823936964227),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6940626790623733040),
        name: 'cardId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7218148758608428894),
        name: 'cardTitle',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6818238693194862684),
        name: 'category',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(5, 33781707284594946),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3551168850071315000),
        name: 'durationSeconds',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2848190549496386803),
        name: 'wasCompleted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8072886828325200849),
        name: 'completedAt',
        type: 10,
        flags: 8,
        indexId: const obx_int.IdUid(6, 387520588437224330),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 5722966125934581911),
    name: 'TopicCardEntity',
    lastPropertyId: const obx_int.IdUid(11, 507744649082267577),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6813211587976227466),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 935253998529132188),
        name: 'cardId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(3, 2765883135833707808),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1119146294334806083),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2874398136570892190),
        name: 'category',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(7, 350953893598916744),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6147200757941060950),
        name: 'difficultyRaw',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5661433891812073573),
        name: 'guideJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7337413104489274019),
        name: 'vocabJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8631359680137731513),
        name: 'isCustom',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6556868853110766774),
        name: 'isFavorite',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2241820544297207504),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 507744649082267577),
        name: 'customCategoryId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(4, 1305742701537502733),
        relationField: 'customCategory',
        relationTarget: 'CustomCategoryEntity',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 5722966125934581911),
    lastIndexId: const obx_int.IdUid(7, 350953893598916744),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [4032303328837315379],
    retiredIndexUids: const [],
    retiredPropertyUids: const [8957645094241474468],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CustomCategoryEntity: obx_int.EntityDefinition<CustomCategoryEntity>(
      model: _entities[0],
      toOneRelations: (CustomCategoryEntity object) => [],
      toManyRelations: (CustomCategoryEntity object) => {
        obx_int.RelInfo<TopicCardEntity>.toOneBacklink(
          11,
          object.id,
          (TopicCardEntity srcObject) => srcObject.customCategory,
        ): object.cards,
      },
      getId: (CustomCategoryEntity object) => object.id,
      setId: (CustomCategoryEntity object, int id) {
        object.id = id;
      },
      objectToFB: (CustomCategoryEntity object, fb.Builder fbb) {
        final categoryIdOffset = fbb.writeString(object.categoryId);
        final nameOffset = fbb.writeString(object.name);
        final iconEmojiOffset = fbb.writeString(object.iconEmoji);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, categoryIdOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, iconEmojiOffset);
        fbb.addInt64(4, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final categoryIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final iconEmojiParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
          isUtc: true,
        );
        final object = CustomCategoryEntity(
          id: idParam,
          categoryId: categoryIdParam,
          name: nameParam,
          iconEmoji: iconEmojiParam,
          createdAt: createdAtParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<CustomCategoryEntity>(
          object.cards,
          store,
          obx_int.RelInfo<TopicCardEntity>.toOneBacklink(
            11,
            object.id,
            (TopicCardEntity srcObject) => srcObject.customCategory,
          ),
        );
        return object;
      },
    ),
    PracticeSessionEntity: obx_int.EntityDefinition<PracticeSessionEntity>(
      model: _entities[1],
      toOneRelations: (PracticeSessionEntity object) => [],
      toManyRelations: (PracticeSessionEntity object) => {},
      getId: (PracticeSessionEntity object) => object.id,
      setId: (PracticeSessionEntity object, int id) {
        object.id = id;
      },
      objectToFB: (PracticeSessionEntity object, fb.Builder fbb) {
        final sessionIdOffset = fbb.writeString(object.sessionId);
        final cardIdOffset = fbb.writeString(object.cardId);
        final cardTitleOffset = fbb.writeString(object.cardTitle);
        final categoryOffset = fbb.writeString(object.category);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, sessionIdOffset);
        fbb.addOffset(2, cardIdOffset);
        fbb.addOffset(3, cardTitleOffset);
        fbb.addOffset(4, categoryOffset);
        fbb.addInt64(5, object.durationSeconds);
        fbb.addBool(6, object.wasCompleted);
        fbb.addInt64(7, object.completedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final sessionIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final cardIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final cardTitleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final categoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final durationSecondsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final wasCompletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final completedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
          isUtc: true,
        );
        final object = PracticeSessionEntity(
          id: idParam,
          sessionId: sessionIdParam,
          cardId: cardIdParam,
          cardTitle: cardTitleParam,
          category: categoryParam,
          durationSeconds: durationSecondsParam,
          wasCompleted: wasCompletedParam,
          completedAt: completedAtParam,
        );

        return object;
      },
    ),
    TopicCardEntity: obx_int.EntityDefinition<TopicCardEntity>(
      model: _entities[2],
      toOneRelations: (TopicCardEntity object) => [object.customCategory],
      toManyRelations: (TopicCardEntity object) => {},
      getId: (TopicCardEntity object) => object.id,
      setId: (TopicCardEntity object, int id) {
        object.id = id;
      },
      objectToFB: (TopicCardEntity object, fb.Builder fbb) {
        final cardIdOffset = fbb.writeString(object.cardId);
        final titleOffset = fbb.writeString(object.title);
        final categoryOffset = fbb.writeString(object.category);
        final difficultyRawOffset = fbb.writeString(object.difficultyRaw);
        final guideJsonOffset = fbb.writeString(object.guideJson);
        final vocabJsonOffset = fbb.writeString(object.vocabJson);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, cardIdOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, categoryOffset);
        fbb.addOffset(4, difficultyRawOffset);
        fbb.addOffset(5, guideJsonOffset);
        fbb.addOffset(6, vocabJsonOffset);
        fbb.addBool(7, object.isCustom);
        fbb.addBool(8, object.isFavorite);
        fbb.addInt64(9, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(10, object.customCategory.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final cardIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final categoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final difficultyRawParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final guideJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final vocabJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final isCustomParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final isFavoriteParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          20,
          false,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
          isUtc: true,
        );
        final object = TopicCardEntity(
          id: idParam,
          cardId: cardIdParam,
          title: titleParam,
          category: categoryParam,
          difficultyRaw: difficultyRawParam,
          guideJson: guideJsonParam,
          vocabJson: vocabJsonParam,
          isCustom: isCustomParam,
          isFavorite: isFavoriteParam,
          createdAt: createdAtParam,
        );
        object.customCategory.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        object.customCategory.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CustomCategoryEntity] entity fields to define ObjectBox queries.
class CustomCategoryEntity_ {
  /// See [CustomCategoryEntity.id].
  static final id = obx.QueryIntegerProperty<CustomCategoryEntity>(
    _entities[0].properties[0],
  );

  /// See [CustomCategoryEntity.categoryId].
  static final categoryId = obx.QueryStringProperty<CustomCategoryEntity>(
    _entities[0].properties[1],
  );

  /// See [CustomCategoryEntity.name].
  static final name = obx.QueryStringProperty<CustomCategoryEntity>(
    _entities[0].properties[2],
  );

  /// See [CustomCategoryEntity.iconEmoji].
  static final iconEmoji = obx.QueryStringProperty<CustomCategoryEntity>(
    _entities[0].properties[3],
  );

  /// See [CustomCategoryEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<CustomCategoryEntity>(
    _entities[0].properties[4],
  );

  /// see [CustomCategoryEntity.cards]
  static final cards =
      obx.QueryBacklinkToMany<TopicCardEntity, CustomCategoryEntity>(
        TopicCardEntity_.customCategory,
      );
}

/// [PracticeSessionEntity] entity fields to define ObjectBox queries.
class PracticeSessionEntity_ {
  /// See [PracticeSessionEntity.id].
  static final id = obx.QueryIntegerProperty<PracticeSessionEntity>(
    _entities[1].properties[0],
  );

  /// See [PracticeSessionEntity.sessionId].
  static final sessionId = obx.QueryStringProperty<PracticeSessionEntity>(
    _entities[1].properties[1],
  );

  /// See [PracticeSessionEntity.cardId].
  static final cardId = obx.QueryStringProperty<PracticeSessionEntity>(
    _entities[1].properties[2],
  );

  /// See [PracticeSessionEntity.cardTitle].
  static final cardTitle = obx.QueryStringProperty<PracticeSessionEntity>(
    _entities[1].properties[3],
  );

  /// See [PracticeSessionEntity.category].
  static final category = obx.QueryStringProperty<PracticeSessionEntity>(
    _entities[1].properties[4],
  );

  /// See [PracticeSessionEntity.durationSeconds].
  static final durationSeconds =
      obx.QueryIntegerProperty<PracticeSessionEntity>(
        _entities[1].properties[5],
      );

  /// See [PracticeSessionEntity.wasCompleted].
  static final wasCompleted = obx.QueryBooleanProperty<PracticeSessionEntity>(
    _entities[1].properties[6],
  );

  /// See [PracticeSessionEntity.completedAt].
  static final completedAt = obx.QueryDateProperty<PracticeSessionEntity>(
    _entities[1].properties[7],
  );
}

/// [TopicCardEntity] entity fields to define ObjectBox queries.
class TopicCardEntity_ {
  /// See [TopicCardEntity.id].
  static final id = obx.QueryIntegerProperty<TopicCardEntity>(
    _entities[2].properties[0],
  );

  /// See [TopicCardEntity.cardId].
  static final cardId = obx.QueryStringProperty<TopicCardEntity>(
    _entities[2].properties[1],
  );

  /// See [TopicCardEntity.title].
  static final title = obx.QueryStringProperty<TopicCardEntity>(
    _entities[2].properties[2],
  );

  /// See [TopicCardEntity.category].
  static final category = obx.QueryStringProperty<TopicCardEntity>(
    _entities[2].properties[3],
  );

  /// See [TopicCardEntity.difficultyRaw].
  static final difficultyRaw = obx.QueryStringProperty<TopicCardEntity>(
    _entities[2].properties[4],
  );

  /// See [TopicCardEntity.guideJson].
  static final guideJson = obx.QueryStringProperty<TopicCardEntity>(
    _entities[2].properties[5],
  );

  /// See [TopicCardEntity.vocabJson].
  static final vocabJson = obx.QueryStringProperty<TopicCardEntity>(
    _entities[2].properties[6],
  );

  /// See [TopicCardEntity.isCustom].
  static final isCustom = obx.QueryBooleanProperty<TopicCardEntity>(
    _entities[2].properties[7],
  );

  /// See [TopicCardEntity.isFavorite].
  static final isFavorite = obx.QueryBooleanProperty<TopicCardEntity>(
    _entities[2].properties[8],
  );

  /// See [TopicCardEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<TopicCardEntity>(
    _entities[2].properties[9],
  );

  /// See [TopicCardEntity.customCategory].
  static final customCategory =
      obx.QueryRelationToOne<TopicCardEntity, CustomCategoryEntity>(
        _entities[2].properties[10],
      );
}
